### ISSUE TITLE
Add a check to make sure simulators passed to HyperMaxentModel can take batched data.

### ISSUE THREAD

**Issue by RainierBarrett** [ur-whitelab/maxent#9]
Right now, if you naively pass in a `simulate()` method to `HyperMaxentModel` and try to use batched data, you get some confusing errors about indexing arising from the backend. The cause of this is pretty non-obvious, so we should instead check the simulator method is able to take data of different batch sizes and return something in the same shape like we expect. Ideally the error will guide users on how to correct this, i.e. explicitly state that you must treat the leading dimension as the batch dimension.

**Comment by whitead** [comment]
Closed by #15
